from setuptools import setup, find_packages
import os

setup(
    name="malware-detector",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "annotated-types",
        "anyio",
        "blinker",
        "certifi",
        "cffi",
        "charset-normalizer",
        "click",
        "colorama",
        "cryptography",
        "distro",
        "Flask",
        "flask-cors",
        "greenlet",
        "groq",
        "h11",
        "httpcore",
        "httpx",
        "idna",
        "itsdangerous",
        "Jinja2",
        "jsonpatch",
        "jsonpointer",
        "langchain",
        "langchain-core",
        "langchain-groq",
        "langchain-text-splitters",
        "langsmith",
        "lxml",
        "MarkupSafe",
        "olefile",
        "orjson",
        "packaging",
        "pdfminer.six",
        "scikit-learn",
        "python-magic-bin",
        "pdfplumber",
        "yara-python",
        "requests-toolbelt",
        "python-docx",
        "openpyxl",
        "python-pptx",
        "tk",
    ],
    entry_points={
        "console_scripts": [
            "malware-detect = malware_detector.cli:main",
            "malware-detect-Threatshield = malware_detector.cli:main",
        ],
    },
    author="Viraj",
    author_email="virajvora2409@gmail.com",
    description="A CLI tool for detecting malicious files",
    long_description=open("README.md").read() if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
)